---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/setup-mac
  label: Setup mac
  create: all
  match: "**/*"
- type: directory
  path: content/week2
  label: Week2
  create: all
  match: "**/*"
- type: directory
  path: content/week3
  label: Week3
  create: all
  match: "**/*"
- type: directory
  path: content/prereqs
  label: Prereqs
  create: all
  match: "**/*"
- type: directory
  path: content/week1
  label: Week1
  create: all
  match: "**/*"
- type: directory
  path: content/tools
  label: Tools
  create: all
  match: "**/*"
- type: directory
  path: content/setup-windows
  label: Setup windows
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.37.1
